[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch",
    "numpy",
    "plyfile",
    "trimesh",
    "tqdm",
    "zstandard",
    "easydict"
]
build-backend = "setuptools.build_meta"


[project]
name = "o_voxel"
version = "0.0.1"
description = "All about voxel."
requires-python = ">=3.8"
authors = [
    { name = "Jianfeng Xiang", email = "belljig@outlook.com" }
]
dependencies = [
    "torch",
    "numpy",
    "plyfile",
    "trimesh",
    "tqdm",
    "zstandard",
    "easydict",
    "cumesh @ git+https://github.com/rwfsmith/CuMesh.git@683440c8d3959653384647e7bb7218dbd99eecca",
    "flex_gemm @ git+https://github.com/rwfsmith/FlexGEMM.git@7598fe133f5b1425d5624b4c00e1f381412b96ce",
]
